language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: SmhV1igeY0F3PIw0Ni3x7xghPD03813KkgwK/pMlekURLFaK3XzmRjiBfwCUW8FOtbpNFh22s6oREDMp5uYl38sWW17C4nv5Nau3NO+2dTxAL8Dt4opD5rIW8dHALqXM9wPTW+4Ls46iNWU0cvhgE5410lXL5mH+ohxUdz63hg0uandHPOgZiEZN8QEyWICc5fFE2EvFU/4mwmIXosNHcqExQWEBaF5YzfSeI2Fb0k78e5g9mRhWGDygXb3qlx2T1qQ3nPMgggfjtQqadJJhXZz6NvEbzeNdBEdAOshs/zekzBb8L5XlQ68N2davbUx8UQBJflcc8mFIBVcG9+DRdf+w1ad0dBAXv+y6Cz6dMN/40bUk9cOKx4WEdDpeSM9CH1ytOLQKO0uWFDVwbgu0Vu9jfHDuS/hL6aZuqa3DJH18BMrM1MfJO19kgHuXb6sCRsWDfYUPkmOA1n6XbMSvXbPE+B6/vNoTCseAnOdmZjakHta8ER4Vdm/Ta7tzNXQzG3EROiSq0PnA8B+1hqWpM2FG03iFpYk4Xw5HSdHct14RRl28+/F4MZ9ivaMApbPdopeVynQ3+AR+UyQixALbBpG1JgI9k9l9v9dDDif/WbEXRI204vUrbk8RHc3ek8ANPghJiCndXlFhICOeFuhnqXmv8T2ZuSFygVtdRHd1vcc=
  app: evening-falls-16772
  on:
    repo: Acosta816/react-trello-testing
  skip_cleanup: 'true'
